//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SASPress.CustomTasks.DS2Datalines {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SASPress.CustomTasks.DS2Datalines.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted SAS data set to DATA step program..
        /// </summary>
        internal static string ConvertedData {
            get {
                return ResourceManager.GetString("ConvertedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Read {0:0,0} columns and {1:0,0} rows of data.
        /// </summary>
        internal static string ConvertedDataMetrics {
            get {
                return ResourceManager.GetString("ConvertedDataMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Exception while converting data source. \r\nDetails:{0}.
        /// </summary>
        internal static string ErrorDuringConversion {
            get {
                return ResourceManager.GetString("ErrorDuringConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*This program was generated from {0} */.
        /// </summary>
        internal static string ProgramHeader {
            get {
                return ResourceManager.GetString("ProgramHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* values are omitted from this preview mode */.
        /// </summary>
        internal static string ValuesOmitted {
            get {
                return ResourceManager.GetString("ValuesOmitted", resourceCulture);
            }
        }
    }
}
